### ISSUE TITLE
Move the script to AzerothCore

### ISSUE THREAD

**Issue by catontheway** [trickerer/boss_runeworder#1]
Hey trickerer, I think your script is amazing, today I found it but I wasn't able to test it since my server is running in AzerothCore, I tried to make it works, but since I'm pretty newbie with C++ and AC/TC core functionalities, I wasn't able to.
I hope you can find a way to do this in AzerothCore, I will try to test it for you if you want, we have a small amount of people (like 20~) but I will do my best to test this until we got it working if that helps, or I will do any other thing that you want from me so this can be "merged" with AzerothCore.

Hope there is a way, and if not, I really appreciate your basecode anyways, thanks!.

**Comment by trickerer** [comment]
[Check it out](https://github.com/trickerer/boss_runeworder/releases/tag/1.0.10) (only script itself is changed, and a new diff for AC `custom_script_loader.cpp`)

**Comment by trickerer** [comment]
Considering it done
