### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by gswxy** [trickerer/boss_runeworder#2]
I use the latest source code （azerothcore），but i got an error when compiling :
/root/azerothcore/src/server/scripts/Custom/boss_runeworder.cpp:536:58: fatal error: called object type 'uint8' (aka 'unsigned char') is not a function or function pointer
        type(m_type),strokeSequence(m_strokes.data(),size(N)), minSize(get_min_size(m_strokes))

**Comment by trickerer** [comment]
1. You are using an older version of the script
2. AzerothCore does indeed have a compile error in runeworder script, but it is regarding a change in Unit_AI target selection defines from 29.12.2021

Fixed in [1.0.11](https://github.com/trickerer/boss_runeworder/releases/tag/1.0.11)

**Comment by gswxy** [comment]
Thank you so much,but i didn't find this file(boss_runeworder.cpp)in the compressed package
Runeworder\server

**Comment by trickerer** [comment]
My bad, packed it without looking. It's fixed now
